#define EQ                               1
#define PLUS                             2
#define MINUS                            3
#define MULT                             4
#define DIV                              5
#define LAPREN                           6
#define RPAREN                           7
#define LIST                             8
#define LPAREN                           9
#define SIN                             10
#define ASIN                            11
#define SINH                            12
#define COS                             13
#define ACOS                            14
#define COSH                            15
#define TAN                             16
#define ATAN                            17
#define TANH                            18
#define COT                             19
#define EXP                             20
#define LOG                             21
#define LN                              22
#define POW                             23
#define COMMA                           24
#define SQRT                            25
#define CBRT                            26
#define CEIL                            27
#define FLOOR                           28
#define MOD                             29
#define ABS                             30
#define VAR                             31
#define PI                              32
#define INT                             33
#define FLOAT                           34
#define DUMMY                           35
