#define EQ                               1
#define INT                              2
#define FLOAT                            3
#define UNKNOWN                          4
#define CONST                            5
#define LETTER                           6
#define AND                              7
#define OR                               8
#define NOT                              9
#define PLUS                            10
#define MINUS                           11
#define MULT                            12
#define DIV                             13
#define MOD                             14
#define FACT                            15
#define EXP                             16
#define LAPREN                          17
#define RPAREN                          18
#define ANY                             19
#define EOQ                             20
#define LPAREN                          21
