#define EQ                               1
#define PLUS                             2
#define MINUS                            3
#define MULT                             4
#define DIV                              5
#define MOD                              6
#define FACT                             7
#define EXP                              8
#define LAPREN                           9
#define RPAREN                          10
#define ANY                             11
#define LETTER                          12
#define INT                             13
#define FLOAT                           14
#define CONST                           15
#define LPAREN                          16
