/* Generated by re2c 1.0.1 on Mon Aug 12 11:42:59 2019 */
#line 1 "euler/parser/tokenizer.re"
#include "grammar.h"
#include "tokenizer.h"

#define FILL_LEX(q) YYCURSOR = q

char *YYCURSOR;

static int lex(void)
{
	char *YYMARKER, *o1;

	// Settings
	
	
#line 18 "euler/parser/tokenizer.c"
{
	char yych;
	unsigned int yyaccept = 0;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '!':	goto yy6;
	case '#':	goto yy8;
	case '(':	goto yy10;
	case ')':	goto yy12;
	case '*':	goto yy14;
	case '+':	goto yy16;
	case '-':	goto yy18;
	case '/':	goto yy20;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy22;
	case '^':	goto yy25;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy27;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
	o1 = YYCURSOR;
#line 46 "euler/parser/tokenizer.re"
	{ return symbol_table_append(EOL, o1); }
#line 77 "euler/parser/tokenizer.c"
yy4:
	++YYCURSOR;
#line 47 "euler/parser/tokenizer.re"
	{ return UNKNOWN; }
#line 82 "euler/parser/tokenizer.c"
yy6:
	++YYCURSOR;
	o1 = YYCURSOR;
#line 39 "euler/parser/tokenizer.re"
	{ return symbol_table_append(FACT, o1); }
#line 88 "euler/parser/tokenizer.c"
yy8:
	++YYCURSOR;
	o1 = YYCURSOR;
#line 40 "euler/parser/tokenizer.re"
	{ return symbol_table_append(MOD, o1); }
#line 94 "euler/parser/tokenizer.c"
yy10:
	++YYCURSOR;
	o1 = YYCURSOR;
#line 41 "euler/parser/tokenizer.re"
	{ return symbol_table_append(LPAREN, o1); }
#line 100 "euler/parser/tokenizer.c"
yy12:
	++YYCURSOR;
	o1 = YYCURSOR;
#line 42 "euler/parser/tokenizer.re"
	{ return symbol_table_append(RPAREN, o1); }
#line 106 "euler/parser/tokenizer.c"
yy14:
	++YYCURSOR;
	o1 = YYCURSOR;
#line 36 "euler/parser/tokenizer.re"
	{ return symbol_table_append(MULT, o1); }
#line 112 "euler/parser/tokenizer.c"
yy16:
	++YYCURSOR;
	o1 = YYCURSOR;
#line 34 "euler/parser/tokenizer.re"
	{ return symbol_table_append(PLUS, o1); }
#line 118 "euler/parser/tokenizer.c"
yy18:
	++YYCURSOR;
	o1 = YYCURSOR;
#line 35 "euler/parser/tokenizer.re"
	{ return symbol_table_append(MINUS, o1);  }
#line 124 "euler/parser/tokenizer.c"
yy20:
	++YYCURSOR;
	o1 = YYCURSOR;
#line 37 "euler/parser/tokenizer.re"
	{ return symbol_table_append(DIV, o1); }
#line 130 "euler/parser/tokenizer.c"
yy22:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy29;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy22;
	default:	goto yy24;
	}
yy24:
	o1 = YYCURSOR;
#line 28 "euler/parser/tokenizer.re"
	{ return symbol_table_append(INT, o1); }
#line 152 "euler/parser/tokenizer.c"
yy25:
	++YYCURSOR;
	o1 = YYCURSOR;
#line 38 "euler/parser/tokenizer.re"
	{ return symbol_table_append(EXP, o1); }
#line 158 "euler/parser/tokenizer.c"
yy27:
	++YYCURSOR;
	o1 = YYCURSOR;
#line 30 "euler/parser/tokenizer.re"
	{ return symbol_table_append(LETTER, o1); }
#line 164 "euler/parser/tokenizer.c"
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy31;
	default:	goto yy30;
	}
yy30:
	YYCURSOR = YYMARKER;
	if (yyaccept == 0) {
		goto yy24;
	} else {
		goto yy33;
	}
yy31:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy31;
	case 'E':
	case 'e':	goto yy34;
	default:	goto yy33;
	}
yy33:
	o1 = YYCURSOR;
#line 29 "euler/parser/tokenizer.re"
	{ return symbol_table_append(FLOAT, o1); }
#line 209 "euler/parser/tokenizer.c"
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy35;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy36;
	default:	goto yy30;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy36;
	default:	goto yy30;
	}
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy36;
	default:	goto yy33;
	}
}
#line 49 "euler/parser/tokenizer.re"

}

static void clear_ersl(ersl_t *ersl)
{
	/* reset euler result */
	ersl->status = 0;
	ersl->type = 0;
	ersl->resultn.fraction = 0;
}

void parser_restart(void *parser)
{
	parse_free(parser, free);
	parser = parse_alloc(malloc);
}

void parse_query(char *query, ersl_t *ersl)
{
	void *parser = parse_alloc(malloc);
	char *addr = query;

	clear_ersl(ersl);
	symbol_table_clear();

	FILL_LEX(query);

	symbol_table_init(query);

	printf("token \t| addr \t\t| string \t| float\n");
	printf("rsv \t| %p \t| NULL \t\t|NaN\n", query);

	while (lex() != EOL) {
		parse(parser, get_last_matched_token(), get_double_value(),
		      ersl);
	}
	parse(parser, 0, 0, ersl);
end:
	parse_free(parser, free);
}
