/* Generated by re2c 1.0.1 on Thu Aug 15 02:54:31 2019 */
#line 1 "euler/parser/tokenizer.re"
#include "grammar.h"
#include "tokenizer.h"
#include <stdio.h> /* temporary */

/* Just change of notation */
#define parse Parse
#define parse_free ParseFree
#define parse_alloc ParseAlloc

void *ParseAlloc(void);
void Parse(void *, int, double, ersl_t *);
void ParseFree(void *);

#define FILL_LEX(q) YYCURSOR = q

char *YYCURSOR;

static int lex(void)
{
	char *YYMARKER;

	// Settings
	
	
#line 28 "euler/parser/tokenizer.c"
{
	char yych;
	unsigned int yyaccept = 0;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '!':	goto yy6;
	case '#':	goto yy8;
	case '&':	goto yy10;
	case '(':	goto yy12;
	case ')':	goto yy14;
	case '*':	goto yy16;
	case '+':	goto yy18;
	case '-':	goto yy20;
	case '/':	goto yy22;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy24;
	case '^':	goto yy27;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	case '|':	goto yy31;
	case '~':	goto yy33;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
#line 62 "euler/parser/tokenizer.re"
	{ return symbol_table_append(EOQ, YYCURSOR); }
#line 89 "euler/parser/tokenizer.c"
yy4:
	++YYCURSOR;
#line 63 "euler/parser/tokenizer.re"
	{ return symbol_table_append(UNKNOWN, YYCURSOR); }
#line 94 "euler/parser/tokenizer.c"
yy6:
	++YYCURSOR;
#line 49 "euler/parser/tokenizer.re"
	{ return symbol_table_append(FACT, YYCURSOR); }
#line 99 "euler/parser/tokenizer.c"
yy8:
	++YYCURSOR;
#line 50 "euler/parser/tokenizer.re"
	{ return symbol_table_append(MOD, YYCURSOR); }
#line 104 "euler/parser/tokenizer.c"
yy10:
	++YYCURSOR;
#line 56 "euler/parser/tokenizer.re"
	{ return symbol_table_append(AND, YYCURSOR); }
#line 109 "euler/parser/tokenizer.c"
yy12:
	++YYCURSOR;
#line 51 "euler/parser/tokenizer.re"
	{ return symbol_table_append(LPAREN, YYCURSOR); }
#line 114 "euler/parser/tokenizer.c"
yy14:
	++YYCURSOR;
#line 52 "euler/parser/tokenizer.re"
	{ return symbol_table_append(RPAREN, YYCURSOR); }
#line 119 "euler/parser/tokenizer.c"
yy16:
	++YYCURSOR;
#line 46 "euler/parser/tokenizer.re"
	{ return symbol_table_append(MULT, YYCURSOR); }
#line 124 "euler/parser/tokenizer.c"
yy18:
	++YYCURSOR;
#line 44 "euler/parser/tokenizer.re"
	{ return symbol_table_append(PLUS, YYCURSOR); }
#line 129 "euler/parser/tokenizer.c"
yy20:
	++YYCURSOR;
#line 45 "euler/parser/tokenizer.re"
	{ return symbol_table_append(MINUS, YYCURSOR);  }
#line 134 "euler/parser/tokenizer.c"
yy22:
	++YYCURSOR;
#line 47 "euler/parser/tokenizer.re"
	{ return symbol_table_append(DIV, YYCURSOR); }
#line 139 "euler/parser/tokenizer.c"
yy24:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy35;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy24;
	default:	goto yy26;
	}
yy26:
#line 38 "euler/parser/tokenizer.re"
	{ return symbol_table_append(INT, YYCURSOR); }
#line 160 "euler/parser/tokenizer.c"
yy27:
	++YYCURSOR;
#line 48 "euler/parser/tokenizer.re"
	{ return symbol_table_append(EXP, YYCURSOR); }
#line 165 "euler/parser/tokenizer.c"
yy29:
	++YYCURSOR;
#line 40 "euler/parser/tokenizer.re"
	{ return symbol_table_append(LETTER, YYCURSOR); }
#line 170 "euler/parser/tokenizer.c"
yy31:
	++YYCURSOR;
#line 57 "euler/parser/tokenizer.re"
	{ return symbol_table_append(OR, YYCURSOR); }
#line 175 "euler/parser/tokenizer.c"
yy33:
	++YYCURSOR;
#line 58 "euler/parser/tokenizer.re"
	{ return symbol_table_append(NOT, YYCURSOR); }
#line 180 "euler/parser/tokenizer.c"
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy37;
	default:	goto yy36;
	}
yy36:
	YYCURSOR = YYMARKER;
	if (yyaccept == 0) {
		goto yy26;
	} else {
		goto yy39;
	}
yy37:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy37;
	case 'E':
	case 'e':	goto yy40;
	default:	goto yy39;
	}
yy39:
#line 39 "euler/parser/tokenizer.re"
	{ return symbol_table_append(FLOAT, YYCURSOR); }
#line 224 "euler/parser/tokenizer.c"
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy41;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy42;
	default:	goto yy36;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy42;
	default:	goto yy36;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy42;
	default:	goto yy39;
	}
}
#line 65 "euler/parser/tokenizer.re"

}

static void clear_ersl(ersl_t *ersl)
{
	/* reset euler result */
	ersl->status = 0;
	ersl->type = 0;
	ersl->resultn.fraction = 0;
}

void parser_restart(void *parser)
{
	parse_free(parser);
	parser = parse_alloc();
}

void parse_query(char *query, ersl_t *ersl)
{
	void *parser = parse_alloc();

	clear_ersl(ersl);
	symbol_table_clear();

	FILL_LEX(query);

	symbol_table_init(query);

	printf("token \t| addr \t\t| string \t| float\n");
	printf("rsv \t| %p \t| NULL \t\t|NaN\n", query);

	while (lex() != EOQ) {
		parse(parser, get_last_matched_token(), get_double_value(),
		      ersl);
	}
	parse(parser, EOQ, 0, ersl);
	parse(parser, 0, 0, ersl);
	parse_free(parser);
}
