.TH "euler/inc/_atof.h" 3 "Thu Feb 13 2020" "Euler Computer Algebra System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
euler/inc/_atof.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fB_atof\fP (const char *s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double _atof (const char * s)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Euler Computer Algebra System from the source code\&.
