.TH "euler/src/_itoa.c" 3 "Thu Feb 13 2020" "Euler Computer Algebra System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
euler/src/_itoa.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/euler\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBswap\fP (char *x, char *y)"
.br
.ti -1c
.RI "char * \fBreverse\fP (char *buffer, int i, int j)"
.br
.ti -1c
.RI "void \fBftoa_reverse\fP (char *str, int len)"
.br
.ti -1c
.RI "int \fBintToStr\fP (int x, char str[], int d)"
.br
.ti -1c
.RI "char * \fB_itoa\fP (int \fBvalue\fP, char *buffer)"
.br
.ti -1c
.RI "void \fBftoa\fP (double n, char *res, int afterpoint)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* _itoa (int value, char * buffer)"

.SS "void ftoa (double n, char * res, int afterpoint)"

.SS "void ftoa_reverse (char * str, int len)"

.SS "int intToStr (int x, char str[], int d)"

.SS "char * reverse (char * buffer, int i, int j)"

.SS "void swap (char * x, char * y)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Euler Computer Algebra System from the source code\&.
