.TH "euler/inc/_itoa.h" 3 "Thu Feb 13 2020" "Euler Computer Algebra System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
euler/inc/_itoa.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fB_itoa\fP (int \fBvalue\fP, char *buffer)"
.br
.ti -1c
.RI "void \fBftoa\fP (double n, char *res, int afterpoint)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* _itoa (int value, char * buffer)"

.SS "void ftoa (double n, char * res, int afterpoint)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Euler Computer Algebra System from the source code\&.
