.TH "euler/inc Directory Reference" 3 "Thu Feb 13 2020" "Euler Computer Algebra System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
euler/inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB_atof\&.h\fP"
.br
.ti -1c
.RI "file \fB_itoa\&.h\fP"
.br
.ti -1c
.RI "file \fB_strcpy\&.h\fP"
.br
.ti -1c
.RI "file \fB_strlen\&.h\fP"
.br
.ti -1c
.RI "file \fB_strstr\&.h\fP"
.br
.ti -1c
.RI "file \fBconstant\&.h\fP"
.br
.ti -1c
.RI "file \fBeuler\&.h\fP"
.br
.ti -1c
.RI "file \fBsimplify\&.h\fP"
.br
.ti -1c
.RI "file \fBstrplace\&.h\fP"
.br
.in -1c
