.TH "euler/src/_strstr.c" 3 "Thu Feb 13 2020" "Euler Computer Algebra System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
euler/src/_strstr.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/euler\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBstrstr_compare\fP (char *x, char *y)"
.br
.ti -1c
.RI "char * \fB_strstr\fP (char *x, char *y)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* _strstr (char * x, char * y)"

.SS "int strstr_compare (char * x, char * y)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Euler Computer Algebra System from the source code\&.
