.TH "euler/src/_strcpy.c" 3 "Thu Feb 13 2020" "Euler Computer Algebra System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
euler/src/_strcpy.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/euler\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fB_strcpy\fP (char *tar, char *dest, uint8_t max)"
.br
.ti -1c
.RI "char * \fB_strnncpy\fP (char *dest, char *src, uint8_t n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* _strcpy (char * tar, char * dest, uint8_t max)"

.SS "char* _strnncpy (char * dest, char * src, uint8_t n)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Euler Computer Algebra System from the source code\&.
