.TH "euler/inc/_strlen.h" 3 "Thu Feb 13 2020" "Euler Computer Algebra System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
euler/inc/_strlen.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "uint8_t \fB_strlen\fP (char *s, uint8_t max)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint8_t _strlen (char * s, uint8_t max)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Euler Computer Algebra System from the source code\&.
