.TH "euler/inc/euler.h" 3 "Thu Feb 13 2020" "Euler Computer Algebra System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
euler/inc/euler.h
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBast\fP"
.br
.ti -1c
.RI "struct \fB__attribute__\fP"
.br
.ti -1c
.RI "struct \fB__attribute__\fP"
.br
.ti -1c
.RI "struct \fB__attribute__\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_QUERY_LENGTH\fP   80"
.br
.ti -1c
.RI "#define \fBMAX_AST_BRANCH\fP   100"
.br
.ti -1c
.RI "#define \fBUNIX\fP"
.br
.ti -1c
.RI "#define \fBNULL\fP   ((void *)0)"
.br
.ti -1c
.RI "#define \fBDOUBLE_PRECISION\fP   10"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBestatus_t\fP { \fBNONE\fP = 255, \fB_PDONE\fP, \fB_PAGAIN\fP, \fB_FEX\fP, \fBMTHE\fP = -128, \fBEMPTYQ\fP, \fBSYMNF\fP, \fBMXVQ\fP, \fBNVF\fP, \fBFNF\fP, \fBCNEF\fP, \fBUNDEFR\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBast\fP \fB__attribute__\fP ((packed)) ast_t"
.br
.ti -1c
.RI "void \fBparse_query\fP (ersl_t *ersl)"
.br
.ti -1c
.RI "void \fBeuler_init\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "typedef \fB__attribute__\fP"
.br
.ti -1c
.RI "uint8_t \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   double \fBnumber\fP"
.br
.ti -1c
.RI "   char \fBliteral\fP"
.br
.ti -1c
.RI "} \fBvalue\fP"
.br
.ti -1c
.RI "struct \fBast\fP * \fBleft\fP"
.br
.ti -1c
.RI "struct \fBast\fP * \fBright\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DOUBLE_PRECISION   10"

.SS "#define MAX_AST_BRANCH   100"

.SS "#define MAX_QUERY_LENGTH   80"

.SS "#define NULL   ((void *)0)"

.SS "#define UNIX"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBestatus_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINONE \fP\fP
.TP
\fB\fI_PDONE \fP\fP
.TP
\fB\fI_PAGAIN \fP\fP
.TP
\fB\fI_FEX \fP\fP
.TP
\fB\fIMTHE \fP\fP
.TP
\fB\fIEMPTYQ \fP\fP
.TP
\fB\fISYMNF \fP\fP
.TP
\fB\fIMXVQ \fP\fP
.TP
\fB\fINVF \fP\fP
.TP
\fB\fIFNF \fP\fP
.TP
\fB\fICNEF \fP\fP
.TP
\fB\fIUNDEFR \fP\fP
.SH "Function Documentation"
.PP 
.SS "struct \fBast\fP \fB__attribute__\fP ((packed))"

.SS "void euler_init (void)"

.SS "void parse_query (ersl_t * ersl)"

.SH "Variable Documentation"
.PP 
.SS "typedef    \fB__attribute__\fP"

.SS "struct \fBast\fP* left"

.SS "char literal"

.SS "double number"

.SS "struct \fBast\fP* right"

.SS "uint8_t type"

.SS "union { \&.\&.\&. }   value"

.SH "Author"
.PP 
Generated automatically by Doxygen for Euler Computer Algebra System from the source code\&.
