.TH "euler/parser/grammar.c" 3 "Thu Feb 13 2020" "Euler Computer Algebra System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
euler/parser/grammar.c
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include '\&.\&./inc/euler\&.h'\fP
.br
\fC#include '\&.\&./inc/constant\&.h'\fP
.br
\fC#include '\&.\&./inc/simplify\&.h'\fP
.br
\fC#include 'symbol_table\&.h'\fP
.br
\fC#include 'grammar\&.h'\fP
.br
\fC#include 'ast\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBYYMINORTYPE\fP"
.br
.ti -1c
.RI "struct \fByyStackEntry\fP"
.br
.ti -1c
.RI "struct \fByyParser\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINTERFACE\fP   1"
.br
.ti -1c
.RI "#define \fBYYCODETYPE\fP   unsigned char"
.br
.ti -1c
.RI "#define \fBYYNOCODE\fP   48"
.br
.ti -1c
.RI "#define \fBYYACTIONTYPE\fP   unsigned char"
.br
.ti -1c
.RI "#define \fBYYWILDCARD\fP   37"
.br
.ti -1c
.RI "#define \fBParseTOKENTYPE\fP   ast_t *"
.br
.ti -1c
.RI "#define \fBYYSTACKDEPTH\fP   100"
.br
.ti -1c
.RI "#define \fBParseARG_SDECL\fP   ersl_t *euler ;"
.br
.ti -1c
.RI "#define \fBParseARG_PDECL\fP   , ersl_t *euler"
.br
.ti -1c
.RI "#define \fBParseARG_PARAM\fP   ,euler"
.br
.ti -1c
.RI "#define \fBParseARG_FETCH\fP   ersl_t *euler =yypParser\->euler ;"
.br
.ti -1c
.RI "#define \fBParseARG_STORE\fP   yypParser\->euler =euler ;"
.br
.ti -1c
.RI "#define \fBParseCTX_SDECL\fP"
.br
.ti -1c
.RI "#define \fBParseCTX_PDECL\fP"
.br
.ti -1c
.RI "#define \fBParseCTX_PARAM\fP"
.br
.ti -1c
.RI "#define \fBParseCTX_FETCH\fP"
.br
.ti -1c
.RI "#define \fBParseCTX_STORE\fP"
.br
.ti -1c
.RI "#define \fBYYNSTATE\fP   35"
.br
.ti -1c
.RI "#define \fBYYNRULE\fP   36"
.br
.ti -1c
.RI "#define \fBYYNTOKEN\fP   40"
.br
.ti -1c
.RI "#define \fBYY_MAX_SHIFT\fP   34"
.br
.ti -1c
.RI "#define \fBYY_MIN_SHIFTREDUCE\fP   62"
.br
.ti -1c
.RI "#define \fBYY_MAX_SHIFTREDUCE\fP   97"
.br
.ti -1c
.RI "#define \fBYY_ERROR_ACTION\fP   98"
.br
.ti -1c
.RI "#define \fBYY_ACCEPT_ACTION\fP   99"
.br
.ti -1c
.RI "#define \fBYY_NO_ACTION\fP   100"
.br
.ti -1c
.RI "#define \fBYY_MIN_REDUCE\fP   101"
.br
.ti -1c
.RI "#define \fBYY_MAX_REDUCE\fP   136"
.br
.ti -1c
.RI "#define \fBYY_NLOOKAHEAD\fP   ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))"
.br
.ti -1c
.RI "#define \fByytestcase\fP(X)"
.br
.ti -1c
.RI "#define \fBYY_ACTTAB_COUNT\fP   (342)"
.br
.ti -1c
.RI "#define \fBYY_SHIFT_COUNT\fP   (34)"
.br
.ti -1c
.RI "#define \fBYY_SHIFT_MIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBYY_SHIFT_MAX\fP   (145)"
.br
.ti -1c
.RI "#define \fBYY_REDUCE_COUNT\fP   (22)"
.br
.ti -1c
.RI "#define \fBYY_REDUCE_MIN\fP   (\-40)"
.br
.ti -1c
.RI "#define \fBYY_REDUCE_MAX\fP   (294)"
.br
.ti -1c
.RI "#define \fBYYMALLOCARGTYPE\fP   size_t"
.br
.ti -1c
.RI "#define \fBTOKEN\fP   yyminor"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fByyStackEntry\fP \fByyStackEntry\fP"
.br
.ti -1c
.RI "typedef struct \fByyParser\fP \fByyParser\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBParseTrace\fP (FILE *TraceFILE, char *zTracePrompt)"
.br
.ti -1c
.RI "void \fBParseInit\fP (void *yypRawParser \fBParseCTX_PDECL\fP)"
.br
.ti -1c
.RI "void * \fBParseAlloc\fP (\fBParseCTX_PDECL\fP)"
.br
.ti -1c
.RI "void \fBParseFinalize\fP (void *p)"
.br
.ti -1c
.RI "void \fBParseFree\fP (void *p)"
.br
.ti -1c
.RI "void \fBParse\fP (void *yyp, int yymajor, \fBParseTOKENTYPE\fP yyminor \fBParseARG_PDECL\fP)"
.br
.ti -1c
.RI "int \fBParseFallback\fP (int iToken)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INTERFACE   1"

.SS "#define ParseARG_FETCH   ersl_t *euler =yypParser\->euler ;"

.SS "#define ParseARG_PARAM   ,euler"

.SS "#define ParseARG_PDECL   , ersl_t *euler"

.SS "#define ParseARG_SDECL   ersl_t *euler ;"

.SS "#define ParseARG_STORE   yypParser\->euler =euler ;"

.SS "#define ParseCTX_FETCH"

.SS "#define ParseCTX_PARAM"

.SS "#define ParseCTX_PDECL"

.SS "#define ParseCTX_SDECL"

.SS "#define ParseCTX_STORE"

.SS "#define ParseTOKENTYPE   ast_t *"

.SS "#define TOKEN   yyminor"

.SS "#define YY_ACCEPT_ACTION   99"

.SS "#define YY_ACTTAB_COUNT   (342)"

.SS "#define YY_ERROR_ACTION   98"

.SS "#define YY_MAX_REDUCE   136"

.SS "#define YY_MAX_SHIFT   34"

.SS "#define YY_MAX_SHIFTREDUCE   97"

.SS "#define YY_MIN_REDUCE   101"

.SS "#define YY_MIN_SHIFTREDUCE   62"

.SS "#define YY_NLOOKAHEAD   ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))"

.SS "#define YY_NO_ACTION   100"

.SS "#define YY_REDUCE_COUNT   (22)"

.SS "#define YY_REDUCE_MAX   (294)"

.SS "#define YY_REDUCE_MIN   (\-40)"

.SS "#define YY_SHIFT_COUNT   (34)"

.SS "#define YY_SHIFT_MAX   (145)"

.SS "#define YY_SHIFT_MIN   (0)"

.SS "#define YYACTIONTYPE   unsigned char"

.SS "#define YYCODETYPE   unsigned char"

.SS "#define YYMALLOCARGTYPE   size_t"

.SS "#define YYNOCODE   48"

.SS "#define YYNRULE   36"

.SS "#define YYNSTATE   35"

.SS "#define YYNTOKEN   40"

.SS "#define YYSTACKDEPTH   100"

.SS "#define yytestcase(X)"

.SS "#define YYWILDCARD   37"

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fByyParser\fP  \fByyParser\fP"

.SS "typedef struct \fByyStackEntry\fP \fByyStackEntry\fP"

.SH "Function Documentation"
.PP 
.SS "void Parse (void * yyp, int yymajor, \fBParseTOKENTYPE\fP yyminor ParseARG_PDECL)"

.SS "void* ParseAlloc (\fBParseCTX_PDECL\fP)"

.SS "int ParseFallback (int iToken)"

.SS "void ParseFinalize (void * p)"

.SS "void ParseFree (void * p)"

.SS "void ParseInit (void *yypRawParser ParseCTX_PDECL)"

.SS "void ParseTrace (FILE * TraceFILE, char * zTracePrompt)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Euler Computer Algebra System from the source code\&.
