.TH "euler/inc/strplace.h" 3 "Thu Feb 13 2020" "Euler Computer Algebra System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
euler/inc/strplace.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstrplace\fP (char *s, char *dest, char old, int \fBnumber\fP)"
.br
.ti -1c
.RI "char * \fBstr_replace\fP (char *s, char *oldW, char *newW, char *result)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* str_replace (char * s, char * oldW, char * newW, char * result)"

.SS "void strplace (char * s, char * dest, char old, int number)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Euler Computer Algebra System from the source code\&.
