.TH "euler/parser/tokenizer.h" 3 "Thu Feb 13 2020" "Euler Computer Algebra System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
euler/parser/tokenizer.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/euler\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBparse\fP   \fBParse\fP"
.br
.ti -1c
.RI "#define \fBparse_free\fP   \fBParseFree\fP"
.br
.ti -1c
.RI "#define \fBparse_alloc\fP   \fBParseAlloc\fP"
.br
.ti -1c
.RI "#define \fB__no_priority\fP   0"
.br
.ti -1c
.RI "#define \fB__func_begin\fP   1"
.br
.ti -1c
.RI "#define \fB__func_end\fP   2"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBParseAlloc\fP (void)"
.br
.ti -1c
.RI "void \fBParseTrace\fP (FILE *TraceFILE, char *zTracePrompt)"
.br
.ti -1c
.RI "void \fBParse\fP (void *, int, ast_t *, ersl_t *)"
.br
.ti -1c
.RI "void \fBParseFree\fP (void *)"
.br
.ti -1c
.RI "int \fBlex\fP (symbol_table_t *symbol_table)"
.br
.ti -1c
.RI "void \fBfill_lex\fP (char *q)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __func_begin   1"

.SS "#define __func_end   2"

.SS "#define __no_priority   0"

.SS "#define parse   \fBParse\fP"

.SS "#define parse_alloc   \fBParseAlloc\fP"

.SS "#define parse_free   \fBParseFree\fP"

.SH "Function Documentation"
.PP 
.SS "void fill_lex (char * q)"

.SS "int lex (symbol_table_t * symbol_table)"

.SS "void Parse (void *, int, ast_t *, ersl_t *)"

.SS "void* ParseAlloc (void)"

.SS "void ParseFree (void *)"

.SS "void ParseTrace (FILE * TraceFILE, char * zTracePrompt)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Euler Computer Algebra System from the source code\&.
