.TH "YYMINORTYPE" 3 "Thu Feb 13 2020" "Euler Computer Algebra System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
YYMINORTYPE
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fByyinit\fP"
.br
.ti -1c
.RI "\fBParseTOKENTYPE\fP \fByy0\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBParseTOKENTYPE\fP YYMINORTYPE::yy0"

.SS "int YYMINORTYPE::yyinit"


.SH "Author"
.PP 
Generated automatically by Doxygen for Euler Computer Algebra System from the source code\&.
