.TH "yyStackEntry" 3 "Thu Feb 13 2020" "Euler Computer Algebra System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yyStackEntry
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBYYACTIONTYPE\fP \fBstateno\fP"
.br
.ti -1c
.RI "\fBYYCODETYPE\fP \fBmajor\fP"
.br
.ti -1c
.RI "\fBYYMINORTYPE\fP \fBminor\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBYYCODETYPE\fP yyStackEntry::major"

.SS "\fBYYMINORTYPE\fP yyStackEntry::minor"

.SS "\fBYYACTIONTYPE\fP yyStackEntry::stateno"


.SH "Author"
.PP 
Generated automatically by Doxygen for Euler Computer Algebra System from the source code\&.
